# Site settings
title: Pans Labyrinth
email: pan.pan@xiaoi.com
description: > # this means to ignore newlines until next attribution
      Life isn't a rat race.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pannzh.github.io" # the base hostname & protocol for your site

#author global variable
author:
    name: Pan
    email: pan.pan@xiaoi.com
    simpleIntro: I love cats.


## Default build settings
## Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null
paginate: 5
paginate_path: "page:num"
permalink:     date
timezone:      null

#Others
baiduAccount: ''  #Baidu Analysis Tool
duoshuo: 'pannzh' #Duoshuo comment
comments: true    #Sitewide comment condition
share: false    #Sitewide share condition

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
#markdown:    kramdown
#highlighter: rouge
#lsi:         false
#excerpt_separator: "\n\n"
kramdown:
  input: GFM
  hard_wrap: false

  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Filtering Content
#show_drafts: null
#limit_posts: 10
#future:      false
#unpublished: false

## Plugins
#whitelist: []
gems:      ['jekyll-paginate']
#
## Serving
#detach:  false
#port:    4000
#host:    127.0.0.1
#baseurl: "" # does not include hostname
#
#
#quiet:    false
#defaults: []
#
## Markdown Processors
#rdiscount:
#  extensions: []
#
#redcarpet:
#  extensions: []
#
#

#Not surport by Github
#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style
